name: voli
description: Alles Micro client
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
  provider:
  http:
  url_launcher:
  share:
  cached_network_image:
  photo_view:
  permission_handler:
  
flutter:
  uses-material-design: true